<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "logging"
 *
 * Auto generated by Extension Builder 2014-10-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Logging',
	'description' => '',
	'category' => 'backend',
	'author' => '',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.0.0-7.9.99',
		),
		'conflicts' => array(),
		'suggests' => array(),
	),
);